
package com.babooin.ws.datetime;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerDateTime", targetNamespace = "http://datetime.ws.babooin.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerDateTime {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "getServerDateReturn", targetNamespace = "http://datetime.ws.babooin.com")
    @RequestWrapper(localName = "getServerDate", targetNamespace = "http://datetime.ws.babooin.com", className = "com.babooin.ws.datetime.GetServerDate")
    @ResponseWrapper(localName = "getServerDateResponse", targetNamespace = "http://datetime.ws.babooin.com", className = "com.babooin.ws.datetime.GetServerDateResponse")
    public XMLGregorianCalendar getServerDate();

}
